---
# tasks file for roles/postgresql
- name: Disable Local PostgreSQL Module
  shell: "dnf -y module disable postgresql"

- name: Install Postgres Repo
  package:
    name: "{{ __package }}"
    state: present
    disable_gpg_check: true
  loop:
    - "{{ postgres_rhel8_repo }}"
  loop_control:
    loop_var: __package

- name: Disable Postgresql Module
  command: "dnf -qy module disable postgresql"
  args:
    warn: false

- name: Install Postgres Packages
  package:
    name: "{{ __package }}"
    state: present
    disable_gpg_check: true
  loop:
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package

- name: Check if Postgres is Initialized
  stat:
    path: "{{ postgres_12_data_dir }}/PG_VERSION"
  register: r_postgres_init_dir_state

- when: not r_postgres_init_dir_state.stat.exists
  name: Run Postgres initdb to initialize if postgres not initialized
  command: "{{ postgres_12_bin_path }}/postgresql-12-setup initdb"
  notify: restart_postgres

- name: Setup Postgres for Remote Password Auth
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_12_data_dir }}/pg_hba.conf"
  notify: restart_postgres

- name: Setup Postgres to Listen on Network Interfaces
  lineinfile:
    dest: "{{ postgres_12_data_dir }}/postgresql.conf"
    line: "listen_addresses = '*'"
    insertafter: "#listen_addresses"
  notify: restart_postgres

- name: Setup Postgres as Started and Enabled on Boot.
  service:
    name: "{{ postgres_service }}"
    state: "{{ postgres_service_state | default('started') }}"
    enabled: "{{ postgres_service_enabled | default(true) }}"

- name: Configure Postgres Resources, User, Database etc
  block:
    - name: Setup Postgres Database
      postgresql_db:
        name: "{{ __database.name }}"
        state: "{{ __database.state | default('present') }}"
      loop: "{{ postgres_databases }}"
      loop_control:
        loop_var: __database

    - name: Create Postgres user
      postgresql_user:
        name: "{{ __user.name }}"
        password: "{{ __user.password | default(omit) }}"
        encrypted: true # "{{ __user.encrypted | default(omit) }}"
        priv: "{{ __user.priv | default(omit) }}"
        db: "{{ __user.database | default(omit) }}"
        # role_attr_flags: "{{ __user.role_attr_flags | default(omit) }}"
        state: "{{ __user.state | default('present') }}"
      loop: "{{ postgres_users }}"
      loop_control:
        loop_var: __user
      no_log: "{{ postgres_user_no_log_state | default(false) }}"

  become_user: "{{ postgres_user }}"
