- name: Deploy, Configure, and Populate Postgres Database
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers

  roles:
    - role: firewall
      vars:
        firewall_services:
          - postgresql

    - role: postgresql
