- name: Deploy HAProxy Load Balancer
  hosts: load_balancers
  gather_facts: false
  become: true
  tags:
    - load_balancers

  roles:
    - role: firewall
      vars:
        firewall_services:
          - http
        firewall_tcp_ports:
          - 5000

    - role: haproxy
