- name: Manage OpenStack Servers DNS
  hosts: control_node
  gather_facts: false
  become: false
  collections:
    - gpte.openstack

  roles:
    - openstack_manage_inmemory_inventory

- name: Update resolve.conf
  hosts: load_balancers,app_servers,database_servers
  become: true
  vars:
    GUID: ${GUID}

  tasks:
    - name: Get Control Node Network Settings
      ansible.builtin.setup:
        filter: ansible_default_ipv4
      delegate_facts: true
      delegate_to: control

    - name: Insert DNS IP
      command: >-
        nmcli connection modify "System eth0"
        ipv4.ignore-auto-dns yes
        ipv4.dns {{ ansible_default_ipv4.address }}
        ipv4.dns-search {{ GUID }}.internal

    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
