- name: Build Inventory
  hosts: control_node
  tasks:
    - name: Fetch Instance Info
      os_server_info:
        region_name: "{{ openstack_region | default('regionOne') }}"
      register: r_instances

    - name: Add host to Inventory
      add_host:
        name: "{{ __instance.private_v4 }}"
        group:
          - "{{ __instance.metadata.AnsibleGroup }}"
      loop: "{{ r_instances.openstack_servers }}"
      loop_control:
        loop_var: __instance

- name: Wait for Load Balancer Hosts to become available
  hosts: load_balancers
  gather_facts: false
  tasks:
    - wait_for_connection:
        timeout: 300

- name: Wait for app server hosts to become available
  hosts: app_servers
  gather_facts: false
  tasks:
    - wait_for_connection:
        timeout: 300

- name: Wait for database hosts to become available
  hosts: database_servers
  gather_facts: false
  tasks:
    - wait_for_connection:
        timeout: 300

- name: Test Connectivity
  hosts: load_balancers,app_servers,database_servers
  gather_facts: false
  tasks:
    - name: test ping
      ping:
