---
# tasks file for roles/satellite
- name: Add Subscription
  hosts: load_balancers,database_servers,app_servers
  become: yes
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod

  tasks:
    - name: Gather Network Facts
      setup:
        gather_subset:
          - "network"
      delegate_facts: true
      delegate_to: localhost
      connection: local

    - name: Update DNS IP
      lineinfile:
        state: present
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: "{{ item }}"
      loop:
        - PEERDNS=no
        - DNS1={{ hostvars.localhost.ansible_default_ipv4.address }}
      register: network_update

    - name: Restart Netman
      service:
        name: NetworkManager
        state: restarted
      when: network_update.changed | bool

    - name: Install katello-ca-consumer Package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: true
        state: latest

    - name: Register System and Attach Subscriptions
      redhat_subscription:
        state: present
        activationkey: "{{ satellite_activationkey }}"
        org_id: "{{ satellite_org }}"
        auto_attach: true
